#!/bin/bash
#original author: gobonja
#adapted for apt by Willi Mutschler (wmutschl)
#Major refactoring by Jean De Schacht (xaos522) with a little help from Gemini

# Log Functions
log_debug () {
    $DEBUG && echo "$@"
}

log_syslog() {
    logger -- "timeshift-autosnap-apt: $@"
    log_debug "$@"
}

# ---------- Helper functions ----------

# Argument Cleaner
# strip any word starting with a dash
clean_apt_args() {
    typeset -a raw_args=($1)
    typeset -a clean_args=()
    for arg in "${raw_args[@]}"; do
        # if argument doesn't start with '-', keep it
        [[ "$arg" != -* ]] && clean_args+=("$arg")
    done
    echo "${clean_args[*]}"
}

# Process Tree Walker
# Walk up the process tree for the current process.
# Find out where the DPkg:Pre-Invoke hook is invoked.
# Log results in syslog.
walk_up_the_process_tree() {
    typeset PATTERN="^[[:space:]]*([0-9]+)[[:space:]]+(.*)$"
    typeset -i LEVEL=0
    typeset PARENT_PID="$$"
    typeset -g TRIGGER_CMD=""
    typeset PS_OUT NEXT_LEVEL_PPID ARGS BINARY ACTION PARAMS CLEAN_PARAMS

    while true ; do
        typeset PS_OUT="$(ps -o ppid= -o args= -p $PARENT_PID)"
        # !!! WATCH OUT "Off-by_One logic" !!!
        # PS_OUT now has the PID of the next higher level
        # but the ARGUMENTS from the current level.
        # The ORDER of the following commands is IMPORTANT.
        [[ "$PS_OUT" =~ $PATTERN ]] || break
        typeset NEXT_LEVEL_PPID=${BASH_REMATCH[1]}
        typeset ARGS=${BASH_REMATCH[2]}

        # --- capture the first 'apt' or 'aptd' we find in the stack ---
        if [[ -z "$TRIGGER_CMD" ]]; then
            # Matches: apt/apt-get followed by the action (install/remove/etc) and everything after
            if [[ "$ARGS" =~ ^(sudo[[:space:]]+)?(apt|apt-get)[[:space:]]+(install|remove|purge|dist-upgrade|full-upgrade)[[:space:]]+(.*) ]]; then
                typeset BINARY="${BASH_REMATCH[2]}"
                typeset ACTION="${BASH_REMATCH[3]}"
                typeset PARAMS="${BASH_REMATCH[4]}"

                # Clean the parameters of flags like -y or --quiet
                typeset CLEAN_PARAMS=$(clean_apt_args "$PARAMS")
                TRIGGER_CMD="$BINARY $ACTION $CLEAN_PARAMS"

            elif [[ "$ARGS" =~ /usr/sbin/aptd ]]; then
                TRIGGER_CMD="Aptdaemon (GUI Update)"
            fi
        fi

        # output THIS levels PARENT_PID and ARGS
        log_syslog "#$LEVEL $PARENT_PID $ARGS"
        [[ "$PARENT_PID" == "1" ]] && break
        # set PARENT_PID for the next level
        PARENT_PID=$NEXT_LEVEL_PPID
        (( LEVEL++ ))
    done
}

# trim variable
trim() {
    # using nameref
    typeset -n nref=$1
    nref="${nref##+([[:space:]])}" # Trim leading whitespace
    nref="${nref%%+([[:space:]])}" # Trim trailing whitespace
}

# One-Pass parser
# Parse configuration file and store results in an associative array
load_config() {
    typeset -g -A CONFIG
    if [[ -f "$CONF_FILE" ]]; then
        typeset -a CONF_LINES
        typeset  LINE KEY VAL
        # Non-greedy pattern to match a line in the conf file.
        # When a line has multiple = signs we only only want
        # the text before the first one as first capture group.
        VALID_LINE_PATTERN='^([^=]+)=(.*)$'
        mapfile -t CONF_LINES < "$CONF_FILE"
        for LINE in "${CONF_LINES[@]}"; do
            # Skip empty lines and comments
            [[ -z "$LINE" || "$LINE" =~ ^[[:space:]]*# ]] && continue
            # Split the line on '=' character, non-gready.
            if [[ "$LINE" =~ $VALID_LINE_PATTERN ]]; then {
                KEY="${BASH_REMATCH[1]}"
                VAL="${BASH_REMATCH[2]}"
                trim KEY
                trim VAL
                [[ -z "$VAL" ]] && VAL=""
                CONFIG["$KEY"]="$VAL"
            }
            else {
                # No match - no '=' sign in  LINE.
                log_syslog "Ignore following line in ${CONF_FILE} (does not match PATTERN):"
                log_syslog "$LINE"
           }
            fi
        done
    else {
        log_syslog "$CONF_FILE is not a regular file. Using defaults."
    }
    fi
}

get_property() {
    typeset KEY="$1" TYPE="$2" DEFAULT="$3"
    typeset VAL="${CONFIG[$KEY]}"

    [[ -z "$VAL" ]] && VAL="$DEFAULT"

    case "$TYPE" in
        boolean) [[ "$VAL" =~ ^(true|false)$ ]] || VAL="$DEFAULT" ;;
        integer) [[ "$VAL" =~ ^[0-9]+$ ]] || VAL="$DEFAULT" ;;
        string)  [[ -n "$VAL" ]] || VAL="$DEFAULT" ;;
    esac
    echo "$VAL"
}

run_sync() {
    typeset SRC="$1" DEST="$2"
    typeset -i rc
    log_syslog "rsync -au --delete $SRC $DEST"
    if $DRY_RUN; then
        log_debug "[DRY RUN] Would rsync -au --delete $SRC $DEST"
    else
        mkdir -p "$DEST"
        rc=$?
        [[ $rc -eq 0 ]] || {
            send_desktop_notification "critical" "run_sync failed." "mkdir $DEST returned status $rc. Abort."
            log_syslog "run_sync rc=$rc. Abort."
            trap - EXIT
            exit $rc
        }
        rsync -au --delete "$SRC" "$DEST"
        rc=$?
        [[ $rc -eq 0 ]] || {
            send_desktop_notification "critical" "run_sync failed." "rsync -au --delete $SRC $DEST returned status $?. Abort."
            log_syslog "run_sync rc=$rc. Abort."
            trap - EXIT
            exit $rc
        }
    fi
}

run_timeshift() {
    typeset -i attempt=1
    typeset ts_subcommand
    typeset ts_return_code=
    typeset -g -a ALL_SNAPSHOTS

    ts_subcommand=$1

    # log_debug "timeshift $@"

    # run timeshift command with retries
    while (( attempt <= TS_MAX_ATTEMPTS )); do

        case $ts_subcommand in

            --create )
                timeshift "$@"
                ts_return_code=$?
                ;;

            --list )
                #  To capture the exit status of the timeshift --list command,
                #+ use a standard pipe instead of process substitution.
                #+ We want to capture the timeshift --list status in PIPESTATUS.
                #+ However, to run timeshift --list mapfile without
                #+ using a subshell, we must set
                set +m
                shopt -s lastpipe

                timeshift "$@" 2>&1 | mapfile -t ALL_SNAPSHOTS
                ts_return_code=${PIPESTATUS[0]}
                ;;

            --delete )
                timeshift "$@"
                ts_return_code=$?
                #  Do not retry the timeshift --delete command when it fails.
                #+ Just log an error message and continue.
                #+ Next run of the script will retry the delete.
                (( attempt = $(( attempt + TS_MAX_ATTEMPTS )) ))
                ;;

            * )
                log_syslog "timeshift $ts_subcommand is not supported"
                exit 1
        esac

        if [[ $ts_return_code -eq 0 ]]; then
            break # Success! Exit the retry loop.
        else
            # timeshift command failed
            log_syslog "timeshift $ts_subcommand rc=$ts_return_code (attempt $attempt of $TS_MAX_ATTEMPTS)"
            if (( attempt < TS_MAX_ATTEMPTS )); then
                sleep $TS_WAIT_SECONDS
            fi

            (( attempt++ ))

        fi
    done # end of retries

    if [[ $ts_return_code -ne 0 ]]; then
        case $ts_subcommand in
            --list)
                send_desktop_notification "critical" "timeshift $ts_subcommand failed." "The timeshift $ts_subcommand command failed after $TS_MAX_ATTEMPTS tries. Maybe another instance of timeshift is active that holds the timeshift lock. Check syslog for errors. Abort."
                log_syslog "timeshift $ts_subcommand rc=${ts_return_code}. Abort."
                trap - EXIT
                exit $ts_return_code
                ;;

            --create)
                send_desktop_notification "critical" "timeshift $ts_subcommand failed." "The timeshift $ts_subcommand command failed after $TS_MAX_ATTEMPTS tries. Maybe another instance of timeshift active that holds the timeshift lock. Check syslog for errors."
                log_syslog "timeshift $ts_subcommand rc=${ts_return_code}. Abort."
                trap - EXIT
                exit $ts_return_code
                ;;
            *)
                log_syslog "timeshift $ts_subcommand rc=${ts_return_code}. Ignore."
                ;;
        esac
    else
        log_syslog "timeshift $ts_subcommand rc=${ts_return_code}."
    fi

    return $ts_return_code

} # end of run_timeshift

get_snapshot_age() {
    typeset SNAPSHOT="$1"
    typeset TIMESTAMP
    typeset -i SNAPSHOT_EPOCH
    typeset -i NOW_EPOCH
    # Convert YYYY-MM-DD_HH-MM-SS to YYYY-MM-DD HH:MM:SS
    TIMESTAMP="${SNAPSHOT/_/ }"
    TIMESTAMP="${TIMESTAMP:0:10} ${TIMESTAMP:11:2}:${TIMESTAMP:14:2}:${TIMESTAMP:17:2}"
    typeset -i SNAPSHOT_EPOCH=$(date -u -d "$TIMESTAMP" +%s)
    typeset -i NOW_EPOCH=$(date -u +%s)
    echo $(( NOW_EPOCH - SNAPSHOT_EPOCH ))
}

#  Automatic deletion of auto snapshots.
#+ Using hybrid deletion policy:
#+ Age based but with a Minimum Count safety value.
auto_delete_snapshots() {
    MIN_KEEP=$(get_property "minKeepSnapshots" "integer" 3)
    RETENTION_PERIOD=$(get_property "retentionPeriod" "integer" 604800) # 7 days

    # Calculate how many snapshots we can actually consider for deletion
    # (Total snapshots - Minimum we must keep)
    typeset -i total_count=${#AUTO_SNAPSHOTS[@]}
    typeset -i deletable_limit=$(( total_count - MIN_KEEP ))

    if (( deletable_limit > 0 )); then
        log_syslog "check for snapshots older than $RETENTION_PERIOD seconds (Safety Valve: keeping $MIN_KEEP)..."

        # We iterate through the oldest snapshots first
        for (( i=0; i<deletable_limit; i++ )); do
            SNAPSHOT="${AUTO_SNAPSHOTS[i]}"
            AGE=$(get_snapshot_age "$SNAPSHOT")

            if (( AGE > RETENTION_PERIOD )); then
                if $DRY_RUN; then
                    log_debug "[DRY RUN] Would delete expired snapshot: $SNAPSHOT (Age: $AGE seconds)"
                else
                    log_syslog "delete expired snapshot: $SNAPSHOT (Age: $AGE seconds)."
                    run_timeshift --delete --snapshot "$SNAPSHOT"
                fi
            else
                # Since AUTO_SNAPSHOTS is chronological, once we hit a snapshot
                # younger than the limit, all subsequent ones are also younger.
                log_debug "Snapshot $SNAPSHOT: age is within retention period ($AGE/$RETENTION_PERIOD)."
                log_debug "Break out of the age check loop."
                break
            fi
        done
        log_syslog "check over"
    else
        log_syslog "snapshot count ($total_count) is at or below Safety Valve ($MIN_KEEP). Skip age-based deletion."
    fi
}
send_desktop_notification() {

    function get_active_gui_user() {
        typeset -n nr_gui_user=$1
        typeset -n nr_gui_user_id=$2
        typeset whereami="find_active_gui_user_using_loginctl"

        # have loginctl?
        if ! command -v loginctl >/dev/null; then
            log_debug "${whereami}: command loginctlx not found"
            return 1
        fi

        typeset -a LOGINCTL_USERS
        set +m
        shopt -s lastpipe
        loginctl --no-legend list-users 2>/dev/null | mapfile -t LOGINCTL_USERS
        rc=${PIPESTATUS[0]}
        [[ $rc -eq 0 ]] || {
            log_debug "${whereami}: loginctl rc=$rc"
            return $rc
        }
        typeset item
        typeset pattern="^[[:space:]]*([0-9]+)[[:space:]]*([^[:space:]]+)[[:space:]]+[^[:space:]]+[[:space:]]+([^[:space:]]+)[[:space:]]*$"
        for item in "${LOGINCTL_USERS[@]}"; do
            if [[ "$item" =~ $pattern ]]; then
                active="${BASH_REMATCH[3]}"
                nr_gui_user_id="${BASH_REMATCH[1]}"
                ( [[ "$active" != active ]] || [[ "$user_id" == 0 ]] ) && continue
                nr_gui_user="${BASH_REMATCH[2]}"
                break
            else
                log_debug "${whereami}: ($item) does not match pattern"
            fi
        done
    }

    function get_active_gui_user_fallback() {
        # Find the GUI user for X11 setup (usually the one logged into display :0)
        typeset -n nr_gui_user=$1
        typeset -n nr_gui_user_id=$2
        typeset whereami="find_active_gui_user_using_w"

        # have w?
        if ! command -v w >/dev/null; then
            log_debug "${whereami}: command w not found"
            return 1
        fi

        typeset -a W
        set +m
        shopt -s lastpipe
        w --no-header 2>/dev/null | mapfile -t W
        rc=${PIPESTATUS[0]}
        [[ $rc -eq 0 ]] || {
            log_debug "${whereami}: command w failed rc=$rc"
            return $rc
        }
        typeset item
        typeset pattern="^[[:space:]]*([^[:space:]]+).*$"
        for item in "${W[@]}"; do
            if [[ "$item" =~ $pattern ]]; then
                nr_gui_user="${BASH_REMATCH[1]}"
                [[ "$nr_gui_user" == root ]] && continue
                break
            else
                log_debug "${whereami}: ($item) does not match pattern"
            fi
        done
        nr_gui_user_id=""
        if [[ -n "$nr_gui_user" ]]; then
            # Get the user's ID to access their DBUS session
            nr_gui_user_id=$(id -u "$gui_user")
        fi
    }


    typeset whereami="send_desktop_notification"
    typeset urgency="$1"   # low, normal, critical
    typeset summary="$2"
    typeset body="$3"
    typeset -i rc

    # have notify-send?
    if ! command -v notify-send >/dev/null; then
        log_debug "${whereami}: command notify-send not found"
        return 1
    fi

    typeset gui_user=""
    typeset user_id=""

    get_active_gui_user gui_user user_id

    if [[ -z "${gui_user}" ]]; then
        get_active_gui_user_fallback gui_user user_id
    fi

    # still no gui_user? give up
    if [[ -z "${gui_user}" ]]; then
        log_debug "${whereami}: failed to get gui_user"
        return 1
    fi

    # Execute as the user, pointing to their specific D-Bus bus
    # This works for both X11 and Wayland
    sudo -u "$gui_user" \
         DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/"$user_id"/bus \
         notify-send -u "$urgency" -i "timeshift" "$summary" "$body" \
         -t 10000
    rc=$?
    [[ "$rc" -eq 0 ]] || log_debug "$whereami: notify-send rc=$rc"
    return $rc

} # End of send_desktop_notification

# Argument Parsing
get_options() {
    typeset -g DRY_RUN DEBUG
    while [[ "$#" -gt 0 ]]; do
        case $1 in
            -n|--dry-run) DRY_RUN=true; shift ;;
            -d|--debug) DEBUG=true; shift ;;
            -t|--test-send-notify)
                DEBUG=true
                send_desktop_notification \
                    "normal" "Desktop notification test." \
                    "Testing if desktop notifications work on your system."
                shift
                exit 0 ;;
            -h|--help)
                echo "Usage: $0 [options]"
                echo "Options:"
                echo "  -d, --dry-run          Show what would happen without making changes"
                echo "  -v, --verbose          Show loaded configuration and debug info"
                echo "  -t, --test-send-notify Test desktop notification"
                echo "  -h, --help       Show this help message"
                exit 0 ;;
            *)
                echo "Unknown option $1"
                shift
                exit 1
                ;;
        esac
    done
}

# Execute user-defined scripts in pre/post directories
run_user_hooks() {
    typeset hook_dir="$1"
    typeset description="$2" # pre-snapshot or post-snapshot

    if [[ -d "$hook_dir" ]]; then
        # Sort alphabetically for predictable execution
        for hook in $(ls "$hook_dir" | sort); do
            log_debug "considering $description hook $hook"
            typeset hook_path="$hook_dir/$hook"
            if [[ -x "$hook_path" ]]; then
                if $DRY_RUN; then
                    log_debug "[DRY RUN] Would run $description hook $hook"
                else
                    log_syslog "Executing $description hook: $hook"
                    # Pass TRIGGER_CMD so hooks can be "context-aware"
                    "$hook_path" "$DESCRIPTION"
                    rc=$?
                    if [[ $rc -ne 0 ]]; then
                        send_desktop_notification "critical" "$description hook $hook failed." "The $description hook $hook failed (rc=$rc). Abort."
                        log_syslog "$description hook $hook failed (rc=$rc). Abort."
                        trap - EXIT
                        exit $rc
                    else
                        log_syslog "$description hook $hook finished (rc=$rc)"
                    fi
                fi
            fi
        done
    fi
}

# Global Exit Handler
cleanup_and_notify() {
    typeset exit_code=$?

    # NOTE: for critical errors we already sent a desktop notification and
    # switched off the trap to avoid sending one more notification here..
    # This catches "command not found", "segfaults", "kill" signals, or
    # other errors we did not catch.
    if [[ $exit_code -ne 0 ]]; then
        log_syslog "Script timeshift-autosnap-apt aborted prematurely with exit code $exit_code."
        send_desktop_notification "critical" \
                                  "Autosnap Script Error" \
                                  "Script timeshift-autosnap-apt crashed (Code: $exit_code). The script may not have created a valid timeshift snapshot! The software update is aborted. Check your syslog for errors. When it is not clear why the script has crashed, run 'sudo timeshift-autosnap-apt --debug' for more information."
    fi
}

# End of helper functions

# ---------- Main Execution Logic ----------

# 'EXIT' catches any termination of the script
trap cleanup_and_notify EXIT

# Constants & Initialization
readonly CONF_FILE=/etc/timeshift-autosnap-apt.conf
readonly DATE_PATTERN="[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}-[0-9]{2}-[0-9]{2}"
readonly SCRIPT_TAG="{timeshift-autosnap-apt}" # Forced namespace for our snapshots

# get options
DRY_RUN=false
DEBUG=false
get_options "$@"
$DRY_RUN && log_debug "--- DRY RUN MODE ACTIVE ---"

# load configuration file
typeset -A CONFIG
shopt -s extglob

load_config

# Debug configuration options
if $DEBUG; then
    log_debug "--- DEBUG: Loaded Configuration ---"
    for k in "${!CONFIG[@]}"; do log_debug "  $k = ${CONFIG[$k]}"; done
    log_debug "-----------------------------------"
fi
unset k

# Load Properties into Variables
SKIP_SNAP=$(get_property "skipAutosnap" "boolean" false)
SNAP_BOOT=$(get_property "snapshotBoot" "boolean" false)
SNAP_EFI=$(get_property "snapshotEFI" "boolean" false)
DELETE_OLD=$(get_property "deleteSnapshots" "boolean" true)
MAX_SNAPS=$(get_property "maxSnapshots" "integer" "3")
UPDATE_GRUB=$(get_property "updateGrub" "boolean" false)
USER_NOTE=$(get_property "snapshotDescription" "string" "* unknown caller *")
# Skip creating a new snapshot when the last snapshot is less than
# the configured seconds old
SNAPSHOT_THRESHOLD=$(get_property "snapshotThreshold" "integer" "300")
# timeshift retries configuration:
TS_MAX_ATTEMPTS=$(get_property "timeshiftMaxAttempts" "integer" "3")
TS_WAIT_SECONDS=$(get_property "timeshiftWaitSeconds" "integer" "2")

# early check for exit
[[ $(findmnt / -no fstype) == "overlay" ]] && { log_debug "skipping: Live CD mode."; exit 0; }
[[ -v SKIP_AUTOSNAP ]] && { log_debug "skipping: SKIP_AUTOSNAP env detected."; exit 0; }
$SKIP_SNAP && { log_syslog "skipping: skipAutosnap enabled in config."; exit 0; }

# run sync if configured
$SNAP_BOOT && run_sync "/boot/" "/boot.backup/"
$SNAP_EFI && run_sync "/boot/efi/" "/boot.backup/efi/"

# Determine if we should skip based on SNAPSHOT_THRESHOLD
typeset -a ALL_SNAPSHOTS

# load ALL_SNAPSHOTS (holds ALL lines from the --list command)
run_timeshift --list || exit $?

log_debug "All snapshots: ${#ALL_SNAPSHOTS[@]}"

#  Filter ALL_SNAPSHOTS for auto snapshots using SCRIPT_TAG to distinguish
#+ normal timeshift snapshots from auto snapshots
#+ extract snapshot timestamp
#+ load the result in AUTO_SNAPSHOTS
typeset -a AUTO_SNAPSHOTS=()
# Escape all regular expression special characters in SCRIPT_TAG
# This escapes: . \ [ ] ( ) * + ? ^ $ | { }
ESCAPED_SCRIPT_TAG_PATTERN=$(echo "$SCRIPT_TAG" | sed 's/[.[\*^$()+?{|}]/\\&/g')
for snapshot in "${ALL_SNAPSHOTS[@]}"; do
    if [[ "$snapshot" =~ $ESCAPED_SCRIPT_TAG_PATTERN ]] &&
           [[ "$snapshot" =~ $DATE_PATTERN ]]; then
        AUTO_SNAPSHOTS+=("${BASH_REMATCH[0]}")
    fi
done

unset ALL_SNAPSHOTS

if $DEBUG; then
    log_debug "AUTO_SNAPSHOTS: ${#AUTO_SNAPSHOTS[@]}"
    for snapshot in "${AUTO_SNAPSHOTS[@]}"; do
        log_debug "$snapshot"
    done
fi

# test snapshot threshold
# Do not create a new snapshot when last snapshot is less than SNAPSHOT_THRESHOLD seconds old
CREATE_NEW_SNAPSHOT=true
if (( ${#AUTO_SNAPSHOTS[@]} > 0 )); then
    LAST_SNAP="${AUTO_SNAPSHOTS[-1]}"
    if [[ -n "$LAST_SNAP" ]]; then
        AGE=$(get_snapshot_age "$LAST_SNAP")
        log_syslog "Age of last snapshot: $AGE seconds"
        if (( AGE < SNAPSHOT_THRESHOLD )); then
            log_syslog "SKIP snapshot creation: last snapshot is only $AGE seconds old (Threshold: $SNAPSHOT_THRESHOLD)."
            CREATE_NEW_SNAPSHOT=false
            # do not call auto_delete_snapshots again
            DELETE_OLD=false
            # do not run grub_mkconfig again
            UPDATE_GRUB=false
        fi
    fi
fi

# build dynamic snapshot description
TRIGGER_CMD=""
walk_up_the_process_tree
log_debug "TRIGGER_CMD =  $TRIGGER_CMD"
if [[ -n "$TRIGGER_CMD" ]]; then
    # trim extra whitespace
    trim TRIGGER_CMD
    FINAL_NOTE="$TRIGGER_CMD"
else
    FINAL_NOTE="$USER_NOTE"
fi
# The "Namespace Lock"
DESCRIPTION="$SCRIPT_TAG $FINAL_NOTE"
unset TRIGGER_CMD FINAL_NOTE

# maybe create new snapshot
if $CREATE_NEW_SNAPSHOT; then
    # --- PRE-SNAPSHOT HOOKS ---
    run_user_hooks "/etc/timeshift-autosnap-apt/pre-snapshot.d" "pre-snapshot"
    if $DRY_RUN; then
        log_debug "[DRY RUN] Would create snapshot: $DESCRIPTION"
    else
        run_timeshift --create --comments "$DESCRIPTION" || exit $?
    fi
    # --- POST-SNAPSHOT HOOKS ---
    run_user_hooks "/etc/timeshift-autosnap-apt/post-snapshot.d" "post-snapshot"
fi

# auto delete snapshots.
if $DELETE_OLD; then
    log_debug "call auto_delete_snapshots..."
    auto_delete_snapshots
fi

# update grub.
if $UPDATE_GRUB && command -v grub-mkconfig >/dev/null; then
    if [[ -d /etc/default/grub-btrfs ]] || [[ -f /usr/share/doc/grub-btrfs/README.md ]]; then
        log_syslog "Update grub..."
        $DRY_RUN || {
            grub-mkconfig -o /boot/grub/grub.cfg
            status=$?
            [[ $status -eq 0 ]] || {
                log_syslog "grub-mkconfig failed with status $status."
                send_desktop_notification "critical" "Update grub failed." "Command grub_mkconfig failed. This could make your system unbootable. Check syslog for errors."
                trap - EXIT
                exit 1
            }
        }
    fi
fi

log_syslog "Snapshot cycle completed successfully."

exit 0
